version: '3.8'
services:
  pg_container:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cashmanager
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
  pgadmin_container:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  api_container:
    build:
      context: ../back
      dockerfile: ../back/Dockerfile
    container_name: api_container
    hostname: api_container
    restart: unless-stopped
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true
    environment:
      DB_PORT: 5432
      DB_HOST: pg_container
    links:
      - pg_container
    depends_on:
      - pg_container
  front_container:
    build:
      context: ../front
      dockerfile: ../front/Dockerfile
    container_name: front_container
    hostname: api_container
    restart: unless-stopped
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
       BACK_HOST: api_container
    links:
      - api_container
    depends_on:
      - api_container



