version: '3'

services:
  postgres:
    image: postgres:14.5
    container_name: signlab-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=signlab
    ports:
      - "5432:5432"


  api:
    build:
      dockerfile: Dockerfile
      context: "back"
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - ./back:/app
    ports:
      - "4000:4000"

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: "front"
    volumes:
      - /app/node_modules
      - ./front:/app
    ports:
      - "3000:3000"